### ISSUE TITLE
user story: I want to know if I'll be going on a new cancer drug, the standard drug or a placebo..

### ISSUE THREAD

**Issue by HStewart23** [fac-15/Curenetics#19]

**Comment by zurda** [comment]
@sesola Is this possible for a patient to know if the drug they're on is a placebo without ruining the trial?

**Comment by sesola** [comment]
Hmm. Good question. For many randomised trials, patients are not supposed to know if they are having the real drug or placebo.

For most cancer trials however, due ethical reasons, we don’t offer placebo. So in this case, we can make it known to the patients they will not be having placebo 

Sola

**Comment by sesola** [comment]
A Dr wants to come in to the office next Wednesday for user testing.

Will 10 am work? 

Sola

**Comment by zurda** [comment]
@sesola Sure, Wednesday morning should be great. Thanks for the quick reply
