### ISSUE TITLE
2nd User testing 14/02

### ISSUE THREAD

**Issue by sesola** [fac-15/Curenetics#26]
Hi Team,
Hope you are having a nice weekend? I've just been through the user feedbacks and comments. Please shall we plan to make all/most of the changes recommended before the next testing?

Cheers

Sola

**Comment by sesola** [comment]
Dear Team,

I think I may have got my wires crossed. The 2 doctors who were due to come in for testing this week were actually booked for next week Thurs, 21st of Feb based on the original testing dates that were sent out.

I reckon this gives us opportunity to take our time in building the product well without being too much in a hurry.

What I'm planning to do is to arrange an alternative test group for Friday this week either face-to-face or remotely. I shall keep you informed as I progress with planning this.

Thanks again and apologies

**Comment by HStewart23** [comment]
No worries Sola, we appreciate whatever testers we can get!  Just so you are aware though, after testing on the 21st we may not be able to make too many changes because of time constraints.

**Comment by sesola** [comment]
Thanks Hannah.

Regarding the 21st, I will try and get them in as early as possible. Hopefully not too many changes will be required. 

Kindly let me know once the current build is completed so I could share the link to the product with people who might be interested in testing remotely. Also let me know what times are best to arrange video test sessions for some users, maybe starting from Friday?

Sola

**Comment by sesola** [comment]
Dear Team,

Aside from the 2 face-to-face testers coming in next week Thursday. Another Dr is keen to come in for face to face testing next Wednesday. Will that be possible, say 10am in the morning?

Also, what days and time slots are best to organise video link remote testings? I might have a couple of people interested 

Thanks again

**Comment by HStewart23** [comment]
Hey Sola, 

On Friday early afternoon sometime would be great ! Could you also write us a list of FAQS with answers ? 

Best,
Hannah

**Comment by sesola** [comment]
Dear Team,

As planned, a tester just confirmed he will be coming over to FACS tomorrow morning at 10am. Hope that's ok. 

Thanks

**Comment by HStewart23** [comment]
That's perfect @sesola will we be seeing you too tomorrow?

**Comment by sesola** [comment]
Yes, I will be there. 
Thanks

**Comment by HStewart23** [comment]
Looking forwards to seeing you @sesola! 
Thankyou

**Comment by sesola** [comment]
The doctor who is meant to come in tomorrow morning just cancelled. He had to go to A/E tonight with an unwell relative. He wants to reschedule. 

Nonetheless, we have 2 other testers for Thursday 

I will still be coming in this morning at 10am to have a look at the work and discuss things further, if that’s ok. 

Sola
