### ISSUE TITLE
User stories 

### ISSUE THREAD

**Issue by zurda** [fac-15/Curenetics#3]
- As a user I want to be able to find clinical trials close to me 
- As a patient I want to be able to be reassured using your app to find clinical trials 
- As a user I want to be able to have contact to one of the clinical trial organiser - personalised 
- As a user I want to be able to narrow if access to this clinical trial is free 
- As a user I want to be sure my medical data is secure 
- As an elderly user I want to know if the app is friendly for people in my age group
- As a user I want to be able to share this information with my doctor 
- As a user I want to be aware how long this clinical trial will last 
- As a user I would like to know if I'll be going on a new cancer drug or the standard drug  or placebo 
- As a user I'd like to know if my expenses will be reimbursed while on the trial. 
- As a user I would like to know what kind of side affects I might encounter 
- As a user I would like to know if my other medical problems might interfere with the trial 
- As a user going to a phase 1 trial I want to know what sort of risks I'll be exposed to on this new trial 

- cost of travel 
- side affects 
- engaged medical team - connect with their doctors

**Comment by arrested-developer** [comment]
These look great! Make sure you write up each one as a separate issue with acceptance criteria

**Comment by sesola** [comment]
Regarding some of the stories, I've got few add ons

* As a user I would like to know if I'll be going on a new cancer drug, the standard drug or **placebo**
* As a user who is a senior citizen, I want to know if the **app** is friendly for people in my age group

**Comment by HStewart23** [comment]
We have moved the user stories into an epic issue with the user journey you can find it here 
-> #5
