### ISSUE TITLE
React router usage

### ISSUE THREAD

**Issue by emilyb7** [fac-15/Curenetics#57]
I realise you guys are new to React router, so just some tips to help you:

1.

There's no need to do this `<Route exact path="/" component={() => <Home />} />`

You can just pass the name of your component in as a prop. See [this link](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Route.md)

2. If you _do_ want to pass in additional props to your Route component (such as you are doing for your results route), you can do that using the `render`prop (see the above link for an explanation of how and why you should do this)

3. You don't need to use the `withRouter` to pass the react router props (like history) to your Route components if you do steps 1 and 2 correctly :)

4. withRouter is useful if you want nested child components to have access to router props, and for whatever reason you don't want to pass them down through like three layers of components. But for a project of your size, I'd be surprised if you need it.

**Comment by mr-bagglesworth** [comment]
[render prop info](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Route.md#render-func)

**Comment by mr-bagglesworth** [comment]
Hi Emily,

Is our current implementation (on staging branch) what you had in mind with your above comments?
Thanks.

**Comment by emilyb7** [comment]
perfect 👍
