### ISSUE TITLE
Importing svgs

### ISSUE THREAD

**Issue by emilyb7** [fac-15/Curenetics#58]
Is there any reason why you're using `require` to access your svgs, rather than import statements?

I don't think it's a big concern, but `import` would be more consistent with the rest of your code.

**Comment by mr-bagglesworth** [comment]
Hi Emily,
They were probably required due to one of us googling it, and that being the answer.

- All svgs other than the one in `Home.js` are now embedded, rather imported, allowing us to style them with css
- embedded svgs are marked up with `aria-labelledby="title here"`and a title tag

**Comment by emilyb7** [comment]
Cool, I like the use of `aria-labelledby` :)

Looks like you have a few disused svg files left alongside your components now though. It's good practice to delete unused code and files as you go along. And also make sure you're not leaving unused imports in your files [here](https://github.com/fac-15/Curenetics/blob/staging/src/Components/Header/Header.js) you're still requiring the old svg files
