### ISSUE TITLE
Accessibility checking

### ISSUE THREAD

**Issue by emilyb7** [fac-15/Curenetics#59]
I've seen in your issues that accessibility is a concern (which is great!)

But it doesn't seem like this is something you're checking actively at the moment (e.g. images without an `alt` tag, focusing on some of the buttons is a bit weird...

I would recommend doing some basic accessibility proofing as you go along, otherwise you'll end up with loads of issues at the end of the project, and it's not really something you want to put off.

There are various ways to ensure that checking for basic accessibility mistakes as part of your workflow. An easy choice is to use eslint (e.g. https://www.npmjs.com/package/eslint-plugin-jsx-a11y), but I imagine you've probably learnt about cooler tools at FAC so I'll leave you to decide how you go about this :)

**Comment by mr-bagglesworth** [comment]
[lighthouse report link](blob:chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/26536ffb-1510-4338-a5a4-130ba526f8cc)
