### ISSUE TITLE
Structure of your components/routes in app.js

### ISSUE THREAD

**Issue by emilyb7** [fac-15/Curenetics#61]
Ok, final thing...

I'm not sure about the main app structure. I don't want to confuse you off if this is something you've thought through and it meets your needs, or if you already have plans to change it. But some things to think about...

- Loading state should probably not be a completely separate component outside of your router...
- Do you really want to load in all the trial data before you need it? You should probably aim to show your home page (which is quite basic) as soon possible.

Overall, quite a lot going on it the one component. Getting a good structure will make everything easier to maintain going forwards, and also to test 👌

**Comment by zurda** [comment]
Hi @emilyb7 , we've took some time today to refactor the state in `App.js`. 

We've done a few things which we think address this issue, and we'd love it if you could review it. Here's a summary of what we've done: 

- Moved the Api call from `App.js` to `Results.js`
- Refactored `Results.js` into a class component 
- The api call only runs once the `Results` page renders
- `App.js` state only holds userInfo in the state, and results is now saved inside the results component 

We'd appreciate it if you could review our code and let us know if this issue needs more work.

**Comment by emilyb7** [comment]
Great!

App.js is looking loads better!

Really good that you're only fetching the data when you need it.

I think results.js is looking a little bit complicated still (particularly the logic around what to show if there are no results). It might help to simplify the state a bit, by saving only the array of results (trials), and not the whole response from the API (not sure you need to size property?)

**Comment by emilyb7** [comment]
(feel free to close this if you want to, and do any refactoring where it makes sense to you!)
