### ISSUE TITLE
Mixed content blocked: fetching API from HTTPS

### ISSUE THREAD

**Issue by zurda** [fac-15/Curenetics#63]
Hi @jbrough , we've just deployed an initial version of the project to netify, and we're having trouble viewing the results in the live version since the api is hosted on an http url: 

<img width="1090" alt="screenshot 2019-02-14 at 11 06 57" src="https://user-images.githubusercontent.com/16784959/52783140-e2a8c280-3048-11e9-90ee-bd2e96b1a293.png">

We're going to research a way to get around this tomorrow, but if you have a way to resolve this on your end, or if you have any tips - we'd appreciate any suggestions.

**Comment by emilyb7** [comment]
I've used this before: https://github.com/Rob--W/cors-anywhere/#documentation

It will make your app slower, so probably not a great long-term solution. But it may help if you just want to get something working quickly.
