### ISSUE TITLE
Essential User Info For Search

### ISSUE THREAD

**Issue by sesola** [fac-15/Curenetics#7]
Essential questions :
Gender
Condition(diagnosis)
Age  
Post code
Distance willing to travel
Happy for us to inform your doctor about the results?

**Comment by zurda** [comment]
Hi @sesola , you mentioned both Location and Post code. Is `Postcode` specific enough so we don't repeat ourselves in the form? If it isn't sufficient, can you explain what's the purpose of the `Location` field?

**Comment by sesola** [comment]
Hi Michal,

I think it’s just a repetition. Post code alone should be enough 

Thanks 

Sola
