### ISSUE TITLE
Branding and Logo

### ISSUE THREAD

**Issue by sesola** [fac-15/Curenetics#73]
Hi Team,

How are things with branding and logo design?  I'm happy with whatever you guys deem ok. However, let me know if you need any suggestions etc.

**Comment by HStewart23** [comment]
Hey @sesola, 

I will attach some screenshots of our coloured prototype so you can have a look at what we are aiming for.

Best, 

Hannah 

![screen shot 2019-02-15 at 10 45 20](https://user-images.githubusercontent.com/39189687/52851834-06ced700-310f-11e9-88a1-9458cdf9d298.png)
![screen shot 2019-02-15 at 10 45 12](https://user-images.githubusercontent.com/39189687/52851837-06ced700-310f-11e9-9685-85e42d444b1d.png)
![screen shot 2019-02-15 at 10 45 01](https://user-images.githubusercontent.com/39189687/52851838-06ced700-310f-11e9-8d5b-01a3f67f612b.png)
![screen shot 2019-02-15 at 10 44 51](https://user-images.githubusercontent.com/39189687/52851839-06ced700-310f-11e9-9f1f-060164c14898.png)

**Comment by sesola** [comment]
Thanks Hannah. Will any of the designs and info in the brandbook and this old investment deck be any useful ?
[Curenetics BrandBook.pdf](https://github.com/fac-15/Curenetics/files/2869415/Curenetics.BrandBook.pdf)
[Investment Deck Curenetics.pdf](https://github.com/fac-15/Curenetics/files/2869416/Investment.Deck.Curenetics.pdf)

**Comment by HStewart23** [comment]
No worries Sola! As we only have a week left we probably won't have time to integrate new design things, though your branding is lovely! Of course, you can do what you want with the project after we hand it over to you next Friday so maybe you could implement your branding then?

**Comment by HStewart23** [comment]
Also, we are still having problems with the API and would like to organise a face to face meeting with @jbrough as we didn't manage to see him today. The primary issue is #63 which is preventing us from remotely deploying which in turn prevents us from remotely testing so it's quite important to get that sorted.

**Comment by HStewart23** [comment]
In general though, thank you for being such an involved product owner, we really appreciate how communicative you have been!
