### ISSUE TITLE
Friday: addressing issues and polishing 

### ISSUE THREAD

**Issue by HStewart23** [fac-15/Curenetics#74]
- [x] where the API gets called 
- [x] use render props for routing #57 
- [x] make sure that when rendering address data from API that you handle missing information. (e.g missing postcode) 
- [x] Add save as pdf button for a card (call to action) 
- [x] mockup search filters for results
- [x] click on the card to get to a single view of results. 
- [x] menu scrolling 
- [x] put in summary to card view.
- [x] embed extra svg on homepage
- [x] read through extra feedback on gitter room 
- [x] read through emily feedback on menu

**Comment by mr-bagglesworth** [comment]
[Saving a component as a pdf](https://medium.com/@shivekkhurana/how-to-create-pdfs-from-react-components-client-side-solution-7f506d9dfa6d)
