### ISSUE TITLE
Scheduling User testing this week

### ISSUE THREAD

**Issue by sesola** [fac-15/Curenetics#8]
Hi Guys,

Some good news!  I've found a tester. Looking for 2 more. They are free to do lunch time this Thursday or Friday. However, we will need to go to them . They are based close to Warren Street station

Will this work for the team? 

Thanks 

Sola

**Comment by sesola** [comment]
I got a 2nd tester booked for next week Thursday. More to come for both weeks

**Comment by sesola** [comment]
Sorry to bombard you guys with messages. I can confirm we have 3 testers ready for this Thursday.

Kindly let me know what time works for you. I'm thinking either 12-1 or 1-2pm?

**Comment by HStewart23** [comment]
Great ! Thanks so much @sesola, 12-1 would be better for us. Do you have an address ?

**Comment by sesola** [comment]
Hi Guys,

Please see meeting venue and time

Thursday 7th of February 

12-1pm
UCLH
Atrium ground floor
250 Euston road. 
NW1 2PG. 

I could send a google invite/reminder if its easier.

**Comment by HStewart23** [comment]
Thanks! A reminder isn't necessary, Michal has your phone number, this is Suzanne's phone number just in case +447784036928 you need to contact us on the day. We'll put up a link to the prototype tonight so you can have a look at it. Just a note, we need to be back at Finsbury Park for 16:00. Looking forward to testing tomorrow!

**Comment by sesola** [comment]
Thanks. You should be back before 4.

**Comment by sesola** [comment]
Morning Guys,

How are we getting on? Thanks for all your hard work

**Comment by HStewart23** [comment]
Good morning, we're just running over the test script before we set off. As there are four of us we will split into two teams of two and see each person for a maximum of 20 minutes. We'll see you at 12, thank you for the excellent communication!

**Comment by sesola** [comment]
Thanks for the hard work you've all put in.

Look forward to reviewing the screens
