### ISSUE TITLE
Adding about paragraph to about page 

### ISSUE THREAD

**Issue by zurda** [fac-15/Curenetics#86]
@sesola , we're about to add text to the about page. If you have anything in mind - feel free to add it to this issue.

**Comment by sesola** [comment]
**Match patients to best clinical trials**

In diseases, such as cancer, through our machine learning-driven algorithms, domain expertise and ability to combine cancer molecular profiling data, we are giving patients hope by helping to recruit them to most suitable clinical trials. At the same time helping trial sponsors meet recruitment targets and hence save costs and reduce time to trial completion.

**Data analysis of in cancer**

Huge amounts of patient data are sitting in data silos in the NHS and in various health systems across the world. With relevant ethical approval and consent, we would analyse some of these data relevant to select disease populations and see how we can improve quality of care and access to treatment options or trials that may be previously unknown to patients and their clinicians.

**Comment by sesola** [comment]
My Profile

Dr Sola Adeleke MRCP, MBA
Oncology Research Fellow
Founder and CEO of Curenetics

Sola is the founder of Curenetics (formerly Aurora Medical Innovations) and an NHS England Clinical Entrepreneur . He is an oncologist with extensive experience in clinical trials, a clinical research fellow at UCL and is actively involved in cancer research. 

Sola is devoted to making clinical trials more accessible to patients and clinicians. His team is using cutting edge match algorithms, data filtering techniques and machine learning to match the right patients to the right trials within the NHS

**Comment by sesola** [comment]
I can get my mug shot over to you, if needed.

**Comment by zurda** [comment]
@sesola :) Thanks! We'll add this in today.
