### ISSUE TITLE
Google Docs as CMS

### ISSUE THREAD

**Issue by jbrough** [fac-15/Curenetics#9]
I just found this randomly tonight looking for something else entirely, I never even remembered I had a blog (it didn't last long!), let alone this library. 2008 - haha jeez!

http://gotchunk.blogspot.com/2008/03/drying-up-cms-with-google.html

**Comment by HStewart23** [comment]
Thanks @jbrough! We don't have much experience using Google in this way so this will be a really useful resource.

**Comment by jbrough** [comment]
oh that links really old and won't be helpful.

When the guy suggested it yesterday I thought you had a library you were using already?

It's a good idea but the API for Google Sheets can be a bit finicky. I wrote a node library to do exactly this but it was in a previous job and I no longer have the code.

I can set up an api though if it's helpful

**Comment by HStewart23** [comment]
Oooh thanks for the info @jbrough, the other option we know about it Airtable, have you used that before?

**Comment by HStewart23** [comment]
@jbrough would you be able to send the link for the quiz tree/ mermaid thing, we'd like to mock up a few of the questions our testing

**Comment by jbrough** [comment]
Sorry somethings up with my email notifications, will keep the issues tab open in future.

here's a start of a medical history Q&A:

https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggVERcbkFbSGF2ZSB5b3UgZ290IGEgY29uZmlybWVkIGRpYWdub3NpcyBvZiBwcm9zdGF0ZSBjYW5jZXI_XVxuQS0tPnxub3xCW1BsZWFzZSBzZWUgeW91ciBHUCBhYm91dCB5b3VyIHN5bXB0b21zLl1cbkEtLT58eWVzfENbQXJlIHlvdSBoYXZpbmcgdHJlYXRtZW50P11cbkMtLT58eWVzfFRlc3RRMVtIYXZlIHlvdSBoYWQgYSBiaW9wc3k_XVxuQy0tPnxub3xEW1doaWNoIG9uZSBvZiB0aGVzZSBiZXN0IGRlc2NyaWJlcyB5b3VyIEdQIHZpc2l0czpdXG5ELS0-fHdhdGNoZnVsIHdhaXRpbmd8RVtJIHZpc2l0IHRoZSBkb2N0b3Igd2hlbiBJIGhhdmUgcGFpbiBvciBzeW1wdG9tc11cbkQtLT58YWN0aXZlIHN1cnZlaWxsYW5jZXxGW0kgaGF2ZSByZWd1bGFyIGRvY3RvcnMgdmlzaXRzL3Rlc3RzIF1cbkUtLT5UZXN0UTFcbkYtLT5UZXN0UTFcblRlc3RRMS0tPnx5ZXN8VGVzdFEyW1BsZWFzZSBwcm92aWRlIHlvdXIgUFNBLCBpZiBrbm93bjpdXG5UZXN0UTEtLT58bm98VGVzdFE1XG5UZXN0UTItLT58eWVzfFRlc3RRNWFbUGxlYXNlIHByb3ZpZGUgeW91ciBHbGVhc29uIEdyb3VwIG9yIFNjb3JlLCBpZiBrbm93bjpdXG5UZXN0UTVhLS0-fG5vfFRlc3RRNVxuVGVzdFE1YS0tPnx5ZXN8VGVzdFE1XG5UZXN0UTItLT58bm98VGVzdFE1W0hhdmUgeW91IGhhZCBib2R5IHNjYW5zP11cblRlc3RRNS0tPnxNUkl8cTYoTVJJKVxuVGVzdFE1LS0-fENUfHE3KENUKVxuVGVzdFE1LS0-fEJvbmV8cTgoQm9uZSBTY2FuKVxuRC0tPnxub25lfEpbTmVpdGhlcl1cbkotLT54W1BsZWFzZSBzZWUgeW91ciBHUCBhYm91dCB5b3VyIHN5bXB0b21zLl1cblRlc3RRNS0tPnxuZXh0fHN0YWdlW0F0IHdoYXQgc3RhZ2UgaXMgeW91ciBjYW5jZXI_XVxuc3RhZ2UtLT58dW5rbm93bnxzdGFnZTBbSSBkb24ndCBrbm93XVxuc3RhZ2UtLT58bG9jYWxpc2VkfHN0YWdlMVtMb2NhbGlzZWQgd2l0aGluIHByb3N0YXRlXVxuc3RhZ2UtLT58bG9jYWxseSBhZHZhbmNlZHxzdGFnZTJbTG9jYWxseSBhZHZhbmNlZF1cbnN0YWdlLS0-fG1ldGFzdGF0aWN8c3RhZ2UzW01ldGFzdGF0aWNdXG5zdGFnZS0tPnxuZXh0fGgzYmJbSGF2ZSB5b3UgaGFkIGEgcHJvc3RhdGVjdG9teT9dXG5oM2JiLS0-fHllc3xoM2JbSGF2ZSB5b3UgaGFkIGFueSBvZiB0aGUgZm9sbG93aW5nIGZvY2FsIHRyZWF0bWVudHM_XVxuaDNiYi0tPnxub3xoM2JcbmgzYi0tPnxIaUZ1fGgzYyhIaUZ1IFRoZXJhcHkpXG5oM2ItLT58Y3J5b3xoM2QoQ3J5byBUaGVyYXB5KVxuaDNiLS0-fGhvcm1vbmV8aDNlKEhvcm1vbmUgVGhlcmFweSlcbmgzYi0tPnxuZXh0fGg0YltIYXZlIHlvdSBoYWQgUmFkaW90aGVyYXB5P11cbmg0Yi0tPnxub3xkaDFcbmg0Yi0tPnx5ZXN8aDZiW1BsZWFzZSBzZWxlY3QgeW91ciB0cmVhdG1lbnRzOl1cbmg2Yi0tPnxicmFjaHl0aGVyYXB5fGg2YyhCcmFjaHl0aGVyYXB5KVxuaDZiLS0-fEV4dGVybmFsIGJlYW18aDZkKEV4dGVybmFsIEJlYW0gUmFkaW90aGVyYXB5KVxuaDZiLS0-fE90aGVyfGg2ZShJJ3ZlIGhhZCBSYWRpb3RoZXJhcHkgYnV0IGRvbid0IHJlbWVtYmVyIHdoaWNoIHR5cGUpXG5oNmItLT58bmV4dHxkaDFbRHJ1ZyBIaXN0b3J5XVxuc3RhZ2UwLS0-aDNiXG5zdGFnZTEtLT5oM2JcbnN0YWdlMi0tPnN0YWdlMmFbV2hlcmUgaGFzIHRoZSBjYW5jZXIgc3ByZWFkP11cbnN0YWdlMmEtLT58U2VtaW5hbCB2ZXNpY2xlc3xzdGFnZTJhMShTZW1pbmFsIHZlc2ljbGVzKVxuc3RhZ2UyYS0tPnxCbGFkZGVyfHN0YWdlMmEyKEJsYWRkZXIpXG5zdGFnZTJhLS0-fEx5bXBofHN0YWdlMmEzKEx5bXBoIEdsYW5kcyBjbG9zZSB0byBwcm9zdGF0ZSlcbnN0YWdlMmEtLT58bmV4dHxoM2JjW0hhdmUgeW91IGhhZCBjaGVtb3RoZXJhcHk_XVxuaDNiYy0tPnx5ZXN8aDNiYlxuaDNiYy0tPnxub3xoM2JiXG5zdGFnZTMtLT5oMmNhW1doZXJlIGhhcyB0aGUgY2FuY2VyIHNwcmVhZD9dXG5oMmNhLS0-fEJvbmV8aDJjYWEoQm9uZXMpXG5oMmNhLS0-fEJsYWRkZXJ8aDJjYWIoQmxhZGRlcilcbmgyY2EtLT58THltcGh8aDJjYWMoTHltcGggR2xhbmRzKVxuaDJjYS0tPnxMdW5nfGgyY2FmKEx1bmdzKVxuaDJjYS0tPnxuZXh0fGg1YmNbaGF2ZSB5b3UgaGFkIGNoZW1vdGhlcmFweT9dXG5oNWJjLS0-fG5vfGg2XG5oNWJjLS0-fHllc3xoNWJiW0hhdmUgeW91IGhhZCBhbnkgb2YgdGhlIGZvbGxvd2luZyB0cmVhdG1lbnRzP11cbmg1YmItLT58bmV4dHxoNlxuaDViYi0tPnxEb2NldGF4ZWx8aDViZihEb2NldGF4ZWwpXG5oNWJiLS0-fENhYmF6aXRheGVsfGg1YmQoQ2FiYXppdGF4ZSlcbmg1YmItLT58U2lwdWxldWNlbC1UfGg1YmUoU2lwdWxldWNlbC1UKVxuaDZbSGF2ZSB5b3UgaGFkIGFueSBkcnVnIHRoZXJhcHk_XVxuaDYtLT58QWJpcmF0ZXJvbmV8aDZiZChBYmlyYXRlcm9uZSlcbmg2LS0-fEVuemFsdXRhbWlkZXxoNmJlKEVuemFsdXRhbWlkZSlcbmg2LS0-fFJhZGl1bS0yMjN8aDZiZihSYWRpdW0gMjIzIGluamVjdGlvbiByYWRpb3RoZXJhcHkpXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ

and, not needed just yet, but here's the repo: https://github.com/jbrough/curenetics-history

I made it public. I can integrate the component with what you guys write, assuming we decide to use it at all at this stage.
